apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: todoapp
type: Opaque
data:
  SECRET_KEY: QGUyKHl4KXYmdGdoM19zPTB5amEtaSFkcGVieHN6XmRnNDd4KS1rJmtxXzN6Zio5ZSoK
  # DB connection details pointing to mysql-0 (first StatefulSet pod)
  NAME: dG9kb2Ri                                                         # tododb
  USER: dG9kb3VzZXI=                                                     # todouser
  PASSWORD: dG9kb3Bhc3N3b3Jk                                             # todopassword
  HOST: bXlzcWwtMC5teXNxbC5teXNxbC5zdmMuY2x1c3Rlci5sb2NhbA==           # mysql-0.mysql.mysql.svc.cluster.local
