apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql
type: Opaque
data:
  # MySQL server credentials
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk   # rootpassword
  MYSQL_USER: dG9kb3VzZXI=                 # todouser
  MYSQL_PASSWORD: dG9kb3Bhc3N3b3Jk         # todopassword
  MYSQL_DATABASE: dG9kb2Ri                 # tododb